# Generated by Django 4.2.30 on 2026-06-08 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('sport', models.CharField(max_length=100)),
                ('team', models.CharField(blank=True, default='', max_length=100)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Injured', 'Injured')], default='Active', max_length=20)),
                ('photo', models.ImageField(blank=True, default='', upload_to='athletes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'athletes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(max_length=100)),
                ('venue', models.CharField(blank=True, default='', max_length=200)),
                ('competition_date', models.DateField()),
                ('level', models.CharField(choices=[('Local', 'Local'), ('State', 'State'), ('National', 'National'), ('International', 'International')], default='Local', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'competitions',
                'ordering': ['-competition_date'],
            },
        ),
        migrations.CreateModel(
            name='WeightTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='api.athlete')),
            ],
            options={
                'db_table': 'weight_tracking',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('speed_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('strength_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('endurance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('flexibility_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('agility_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('strength_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('endurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('flexibility_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('agility_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='api.athlete')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=150)),
                ('body_part', models.CharField(max_length=100)),
                ('injury_date', models.DateField()),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Minor', max_length=20)),
                ('recovery_status', models.CharField(choices=[('Recovering', 'Recovering'), ('Recovered', 'Recovered'), ('Ongoing Treatment', 'Ongoing Treatment')], default='Recovering', max_length=30)),
                ('expected_recovery_date', models.DateField(blank=True, null=True)),
                ('actual_recovery_date', models.DateField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True, default='')),
                ('treatment_plan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='api.athlete')),
            ],
            options={
                'db_table': 'injuries',
                'ordering': ['-injury_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('medal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('None', 'None')], default='None', max_length=10)),
                ('score', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_results', to='api.athlete')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.competition')),
            ],
            options={
                'db_table': 'competition_results',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], default='Present', max_length=20)),
                ('session_type', models.CharField(choices=[('Training', 'Training'), ('Competition', 'Competition'), ('Recovery', 'Recovery'), ('Other', 'Other')], default='Training', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.athlete')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-attendance_date'],
                'unique_together': {('athlete', 'attendance_date', 'session_type')},
            },
        ),
    ]
