# Generated by Django 4.2.30 on 2026-07-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=170),
        ),
        migrations.AddConstraint(
            model_name='coursecategory',
            constraint=models.UniqueConstraint(fields=('sport', 'parent', 'slug'), name='unique_category_slug_scope'),
        ),
    ]
