# Generated by Django 4.2.30 on 2026-07-24 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_contactinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('warm_up', 'Warm-Up'), ('activation', 'Activation'), ('strength', 'Strength'), ('power', 'Power'), ('plyometrics', 'Plyometrics'), ('speed', 'Speed'), ('endurance', 'Endurance'), ('sport_specific', 'Sport-Specific Drills'), ('tactical', 'Tactical Session'), ('mobility', 'Mobility'), ('flexibility', 'Flexibility'), ('cool_down', 'Cool-Down'), ('recovery', 'Recovery')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'training_program_blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='api.athlete')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('reps', models.CharField(blank=True, default='', help_text='e.g. "8-10", "AMRAP", "30s"', max_length=50)),
                ('load', models.CharField(blank=True, default='', help_text='e.g. "70% 1RM", "bodyweight", "20kg"', max_length=50)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.programblock')),
            ],
            options={
                'db_table': 'training_program_exercises',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, default='', help_text='e.g. "Week 1 — Monday"', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.trainingprogram')),
            ],
            options={
                'db_table': 'training_program_days',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.AddField(
            model_name='programblock',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='training.programday'),
        ),
        migrations.CreateModel(
            name='ExerciseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('actual_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_reps', models.CharField(blank=True, default='', max_length=50)),
                ('actual_load', models.CharField(blank=True, default='', max_length=50)),
                ('athlete_notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_completions', to='api.athlete')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='training.programexercise')),
            ],
            options={
                'db_table': 'training_exercise_completions',
            },
        ),
        migrations.AddConstraint(
            model_name='programday',
            constraint=models.UniqueConstraint(fields=('program', 'date'), name='unique_program_day_date'),
        ),
        migrations.AddConstraint(
            model_name='exercisecompletion',
            constraint=models.UniqueConstraint(fields=('exercise', 'athlete'), name='unique_exercise_completion'),
        ),
    ]
