# Generated by Django 4.2.30 on 2026-07-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactinquiry'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sleep_quality', models.PositiveSmallIntegerField(help_text='1 (poor) - 5 (excellent)')),
                ('fatigue', models.PositiveSmallIntegerField(help_text='1 (very fatigued) - 5 (very fresh)')),
                ('soreness', models.PositiveSmallIntegerField(help_text='1 (very sore) - 5 (no soreness)')),
                ('stress', models.PositiveSmallIntegerField(help_text='1 (very stressed) - 5 (very relaxed)')),
                ('mood', models.PositiveSmallIntegerField(help_text='1 (poor) - 5 (great)')),
                ('resting_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_checkins', to='api.athlete')),
            ],
            options={
                'db_table': 'training_wellness_checkins',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SessionRPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('rpe', models.PositiveSmallIntegerField(help_text='1 (very light) - 10 (maximal effort)')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('session_type', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_rpe_records', to='api.athlete')),
            ],
            options={
                'db_table': 'training_session_rpe',
                'ordering': ['-session_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='wellnesscheckin',
            constraint=models.UniqueConstraint(fields=('athlete', 'date'), name='unique_wellness_checkin_per_day'),
        ),
    ]
