# Generated by Django 4.2.30 on 2026-07-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_wellnesscheckin_sessionrpe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexercise',
            name='has_3d_demo',
            field=models.BooleanField(default=False, help_text='Flags a 3D model/animation is attached (asset pipeline is a later phase, same as academy.Lesson.has_3d_demo).'),
        ),
        migrations.AddField(
            model_name='programexercise',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Link to a demonstration photo.'),
        ),
        migrations.AddField(
            model_name='programexercise',
            name='model_3d_ref',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programexercise',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Link to a demonstration video (e.g. YouTube).'),
        ),
    ]
