# Generated by Django 4.2.30 on 2026-07-26 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactinquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0003_programexercise_has_3d_demo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('category', models.CharField(choices=[('speed', 'Speed'), ('power', 'Power'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('agility', 'Agility'), ('flexibility', 'Flexibility'), ('body_composition', 'Body Composition')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(help_text='e.g. "seconds", "cm", "reps", "kg", "ml/kg/min"', max_length=30)),
                ('higher_is_better', models.BooleanField(default=True, help_text='False for time-based tests (e.g. a sprint), where a lower value is the better result.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'training_test_protocols',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api.athlete')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='training.testprotocol')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_test_results',
                'ordering': ['-test_date'],
            },
        ),
    ]
