# Generated by Django 4.2.30 on 2026-08-01 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conversation_message_and_more'),
        ('training', '0004_testprotocol_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_intake_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to='api.athlete')),
            ],
            options={
                'db_table': 'training_nutrition_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='nutritionlog',
            constraint=models.UniqueConstraint(fields=('athlete', 'date'), name='unique_nutrition_log_per_day'),
        ),
    ]
