import { useEffect, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { Sparkles, Wand2 } from 'lucide-react'
import { trainingAPI, athletesAPI } from '@/services/api'
import { parseListResponse } from '@/lib/apiHelpers'
import { useToast } from '@/context/ToastContext'
import type { AthleteListItem, GeneratorStatus, ProgramGoal } from '@/types'
import { PageHeader } from '@/components/dashboard/PageHeader'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { Textarea } from '@/components/ui/Textarea'
import { Badge } from '@/components/ui/Badge'

const GOAL_LABELS: Record<ProgramGoal, string> = {
  strength: 'Strength',
  hypertrophy: 'Hypertrophy (Muscle Growth)',
  power: 'Power',
  endurance: 'Endurance',
  speed_agility: 'Speed & Agility',
  general_fitness: 'General Fitness',
  return_to_play: 'Return to Play',
}

const DURATION_OPTIONS = [1, 2, 4, 8, 12, 52]

const todayStr = () => new Date().toISOString().split('T')[0]

export default function GenerateProgram() {
  const navigate = useNavigate()
  const { showToast } = useToast()
  const [athletes, setAthletes] = useState<AthleteListItem[]>([])
  const [status, setStatus] = useState<GeneratorStatus | null>(null)
  const [generating, setGenerating] = useState(false)

  const [form, setForm] = useState({
    athlete: '', sport: '', goal: 'general_fitness' as ProgramGoal,
    duration_weeks: 4, sessions_per_week: 3, start_date: todayStr(),
    experience_level: 'intermediate' as 'beginner' | 'intermediate' | 'advanced',
    equipment_notes: '', injury_notes: '',
  })

  useEffect(() => {
    athletesAPI.getAll().then((res) => setAthletes(parseListResponse(res.data))).catch(() => {})
    trainingAPI.getGeneratorStatus().then((res) => setStatus(res.data)).catch(() => {})
  }, [])

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault()
    if (!form.athlete || !form.sport) return
    setGenerating(true)
    try {
      const res = await trainingAPI.generateProgram({
        ...form,
        athlete: Number(form.athlete),
      })
      showToast(`Program generated (${res.data.generator_mode === 'llm' ? 'AI-assisted' : 'rule-based'}) — review and edit as needed.`, 'success')
      navigate(`/dashboard/training/${res.data.id}`)
    } catch {
      showToast('Failed to generate program', 'error')
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div className="mx-auto max-w-2xl">
      <PageHeader
        title="Generate Training Program"
        description="Build a complete, editable program from a few inputs"
      />

      {status && (
        <Card className="mb-6 flex items-center gap-3 p-4">
          <Sparkles size={18} className="shrink-0 text-accent" />
          <p className="flex-1 font-body text-xs text-text-secondary">
            {status.mode === 'llm'
              ? 'Programs are generated with AI assistance based on your inputs.'
              : 'No AI provider is configured, so programs are generated by a real rule-based periodization engine — not a placeholder. Every day, block, and exercise it creates opens directly in the builder for you to review and adjust.'}
          </p>
          <Badge variant={status.mode === 'llm' ? 'accent' : 'default'}>{status.label}</Badge>
        </Card>
      )}

      <Card className="p-6">
        <form onSubmit={handleSubmit}>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <Select label="Athlete *" value={form.athlete} onChange={(e) => setForm({ ...form, athlete: e.target.value })} required>
              <option value="">Select athlete</option>
              {athletes.map((a) => <option key={a.id} value={a.id}>{a.full_name}</option>)}
            </Select>
            <Input id="gen_sport" label="Sport *" value={form.sport} onChange={(e) => setForm({ ...form, sport: e.target.value })} required placeholder="e.g. Football" />

            <Select label="Goal" value={form.goal} onChange={(e) => setForm({ ...form, goal: e.target.value as ProgramGoal })}>
              {(status?.goals || Object.keys(GOAL_LABELS) as ProgramGoal[]).map((g) => (
                <option key={g} value={g}>{GOAL_LABELS[g] || g}</option>
              ))}
            </Select>
            <Select label="Experience Level" value={form.experience_level} onChange={(e) => setForm({ ...form, experience_level: e.target.value as typeof form.experience_level })}>
              <option value="beginner">Beginner</option>
              <option value="intermediate">Intermediate</option>
              <option value="advanced">Advanced</option>
            </Select>

            <Select label="Duration" value={form.duration_weeks} onChange={(e) => setForm({ ...form, duration_weeks: Number(e.target.value) })}>
              {DURATION_OPTIONS.map((w) => <option key={w} value={w}>{w} week{w > 1 ? 's' : ''}{w === 52 ? ' (annual)' : ''}</option>)}
            </Select>
            <Input id="gen_sessions" type="number" min={1} max={7} label="Sessions per Week" value={form.sessions_per_week} onChange={(e) => setForm({ ...form, sessions_per_week: Number(e.target.value) })} />

            <div className="sm:col-span-2">
              <Input id="gen_start" type="date" label="Start Date *" value={form.start_date} onChange={(e) => setForm({ ...form, start_date: e.target.value })} required />
            </div>

            <div className="sm:col-span-2">
              <Textarea id="gen_equipment" label="Equipment Available" rows={2} placeholder="e.g. Barbell, dumbbells, resistance bands" value={form.equipment_notes} onChange={(e) => setForm({ ...form, equipment_notes: e.target.value })} />
            </div>
            <div className="sm:col-span-2">
              <Textarea id="gen_injuries" label="Injury Considerations" rows={2} placeholder="e.g. Recovering from ankle sprain — avoid high-impact plyometrics" value={form.injury_notes} onChange={(e) => setForm({ ...form, injury_notes: e.target.value })} />
            </div>
          </div>

          <Button type="submit" className="mt-6 w-full" magnetic={false} disabled={generating}>
            <Wand2 size={16} /> {generating ? 'Generating...' : 'Generate Program'}
          </Button>
        </form>
      </Card>
    </div>
  )
}
