/**
 * Reporting System — one-click PDF and Excel exports
 */
import { useState } from 'react'
import { downloadReport, getErrorMessage } from '../services/api'
import { useToast } from '../context/ToastContext'
import { FaFilePdf, FaFileExcel, FaDownload, FaFileAlt, FaBandAid, FaClipboardCheck } from 'react-icons/fa'
import PageHeader from '../components/PageHeader'
import DataErrorPanel from '../components/DataErrorPanel'

const reports = [
  { type: 'athletes', title: 'Athlete Report', desc: 'Complete roster with contact details and status', format: 'pdf', icon: FaFilePdf },
  { type: 'performance', title: 'Performance Report', desc: 'Speed, strength, endurance, agility metrics', format: 'pdf', icon: FaFilePdf },
  { type: 'injuries', title: 'Injury Report', desc: 'Severity, recovery status, and medical notes', format: 'pdf', icon: FaBandAid },
  { type: 'athletes', title: 'Athletes Export', desc: 'Spreadsheet export for roster analysis', format: 'excel', icon: FaFileExcel },
  { type: 'performance', title: 'Performance Export', desc: 'All performance metrics in Excel format', format: 'excel', icon: FaFileExcel },
  { type: 'attendance', title: 'Attendance Export', desc: 'Session records with dates and status', format: 'excel', icon: FaClipboardCheck },
]

export default function Reports() {
  const { showToast } = useToast()
  const [loadError, setLoadError] = useState('')
  const [downloading, setDownloading] = useState('')

  const handleExport = async (report) => {
    setLoadError('')
    setDownloading(`${report.type}-${report.format}`)
    try {
      await downloadReport(report.type, report.format)
      showToast(`${report.title} downloaded`, 'success')
    } catch (err) {
      const msg = getErrorMessage(err, 'Report download failed. Sign in and try again.')
      setLoadError(msg)
      showToast(msg, 'error')
    } finally {
      setDownloading('')
    }
  }

  return (
    <div className="animate-in dashboard-luxury">
      <PageHeader
        title="Reporting Center"
        subtitle="One-click exports · PDF reports · Excel spreadsheets"
      />

      {loadError && <DataErrorPanel message={loadError} onRetry={() => setLoadError('')} retryLabel="Dismiss" />}

      <div className="reports-grid-premium mb-4">
        {reports.map((r) => (
          <div className={`report-card-premium ${r.format}`} key={`${r.type}-${r.format}`}>
            <div className="icon-wrap"><r.icon /></div>
            <h5>{r.title}</h5>
            <p>{r.desc}</p>
            <button
              type="button"
              className={r.format === 'pdf' ? 'btn-export-pdf' : 'btn-export-excel'}
              onClick={() => handleExport(r)}
              disabled={Boolean(downloading)}
            >
              <FaDownload /> {downloading === `${r.type}-${r.format}` ? 'Downloading...' : `Export ${r.format === 'pdf' ? 'PDF' : 'Excel'}`}
            </button>
          </div>
        ))}
      </div>

      <div className="glass-card">
        <div className="d-flex align-items-center gap-3 flex-wrap">
          <FaFileAlt style={{ fontSize: '2rem', color: 'var(--af-gold)' }} />
          <div>
            <h6 className="mb-1">Server-side generation</h6>
            <p className="mb-0 text-muted" style={{ fontSize: '0.85rem' }}>
              Reports are generated by Django (ReportLab / OpenPyXL) with your session credentials.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}