import { useState } from 'react'
import { FileText, FileSpreadsheet, Download, HeartPulse, ClipboardCheck, GraduationCap, Dumbbell } from 'lucide-react'
import { downloadReport, getErrorMessage } from '@/services/api'
import { useToast } from '@/context/ToastContext'
import { PageHeader } from '@/components/dashboard/PageHeader'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'

type ReportFormat = 'pdf' | 'excel'
interface ReportDef { type: string; title: string; desc: string; format: ReportFormat; icon: typeof FileText }

const REPORTS: ReportDef[] = [
  { type: 'athletes', title: 'Athlete Report', desc: 'Complete roster with contact details and status', format: 'pdf', icon: FileText },
  { type: 'performance', title: 'Performance Report', desc: 'Speed, strength, endurance, agility metrics', format: 'pdf', icon: FileText },
  { type: 'injuries', title: 'Injury Report', desc: 'Severity, recovery status, and medical notes', format: 'pdf', icon: HeartPulse },
  { type: 'academy', title: 'Academy Report', desc: 'Course enrollments, progress, and completions', format: 'pdf', icon: GraduationCap },
  { type: 'athletes', title: 'Athletes Export', desc: 'Spreadsheet export for roster analysis', format: 'excel', icon: FileSpreadsheet },
  { type: 'performance', title: 'Performance Export', desc: 'All performance metrics in Excel format', format: 'excel', icon: FileSpreadsheet },
  { type: 'attendance', title: 'Attendance Export', desc: 'Session records with dates and status', format: 'excel', icon: ClipboardCheck },
  { type: 'academy', title: 'Academy Export', desc: 'Enrollment and completion data in Excel format', format: 'excel', icon: GraduationCap },
  { type: 'training', title: 'Training & Monitoring Export', desc: 'Training programs, wellness check-ins, and session RPE', format: 'excel', icon: Dumbbell },
]

export default function Reports() {
  const { showToast } = useToast()
  const [downloading, setDownloading] = useState('')

  const handleExport = async (report: ReportDef) => {
    const key = `${report.type}-${report.format}`
    setDownloading(key)
    try {
      await downloadReport(report.type, report.format)
      showToast(`${report.title} downloaded`, 'success')
    } catch (err) {
      showToast(getErrorMessage(err, 'Report download failed. Sign in and try again.'), 'error')
    } finally {
      setDownloading('')
    }
  }

  return (
    <div>
      <PageHeader title="Reporting Center" description="One-click exports · PDF reports · Excel spreadsheets" />

      <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
        {REPORTS.map((r) => {
          const key = `${r.type}-${r.format}`
          return (
            <Card key={key} className="p-6">
              <div className="flex size-11 items-center justify-center rounded-xl bg-accent-soft text-accent">
                <r.icon size={20} />
              </div>
              <h3 className="mt-4 font-display text-base font-bold text-text">{r.title}</h3>
              <p className="mt-1 font-body text-xs text-text-secondary">{r.desc}</p>
              <Button
                size="sm"
                variant={r.format === 'pdf' ? 'primary' : 'outline'}
                magnetic={false}
                className="mt-4 w-full"
                onClick={() => handleExport(r)}
                disabled={Boolean(downloading)}
              >
                <Download size={14} /> {downloading === key ? 'Downloading...' : `Export ${r.format === 'pdf' ? 'PDF' : 'Excel'}`}
              </Button>
            </Card>
          )
        })}
      </div>

      <Card className="mt-6 flex items-center gap-4 p-6">
        <FileText size={28} className="shrink-0 text-accent" />
        <div>
          <h3 className="font-body text-sm font-semibold text-text">Server-side generation</h3>
          <p className="mt-0.5 font-body text-xs text-text-secondary">
            Reports are generated by Django (ReportLab / OpenPyXL) with your session credentials.
          </p>
        </div>
      </Card>
    </div>
  )
}
